"""generation events ledger

Revision ID: 1d1fa5426c98
Revises: e7506153dde6
Create Date: 2026-08-01 23:35:01.953641
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d1fa5426c98'
down_revision: Union[str, None] = 'e7506153dde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('refund_reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_events_story_id'), ['story_id'], unique=False)
        batch_op.create_index('ix_generation_events_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_events_user_id'))
        batch_op.drop_index('ix_generation_events_user_created')
        batch_op.drop_index(batch_op.f('ix_generation_events_story_id'))
        batch_op.drop_index(batch_op.f('ix_generation_events_created_at'))

    op.drop_table('generation_events')
    # ### end Alembic commands ###
