"""generation event usage telemetry

Revision ID: 6ad627f4c4da
Revises: 2e8f49dd67b9
Create Date: 2026-08-02 15:40:19.643675
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ad627f4c4da'
down_revision: Union[str, None] = '2e8f49dd67b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=20), server_default='', nullable=False))
        batch_op.add_column(sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('images', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_events', schema=None) as batch_op:
        batch_op.drop_column('images')
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
