"""plan interest

Revision ID: 75a4e5ce30bf
Revises: c1c035ea64c4
Create Date: 2026-08-01 23:44:29.769252
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75a4e5ce30bf'
down_revision: Union[str, None] = 'c1c035ea64c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_interest',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('plan_code', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_code', name='uq_plan_interest_user_plan')
    )
    with op.batch_alter_table('plan_interest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_interest_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_interest_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_interest_user_id'))
        batch_op.drop_index(batch_op.f('ix_plan_interest_created_at'))

    op.drop_table('plan_interest')
    # ### end Alembic commands ###
