"""billing subscription state

Revision ID: 8cc694e50351
Revises: 6ad627f4c4da
Create Date: 2026-08-02 18:20:17.475547
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8cc694e50351'
down_revision: Union[str, None] = '6ad627f4c4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('provider_created', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_status', sa.String(length=30), server_default='', nullable=False))
        batch_op.add_column(sa.Column('last_billing_event_at', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_column('last_billing_event_at')
        batch_op.drop_column('stripe_subscription_status')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('plan_expires_at')

    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_billing_events_created_at'))

    op.drop_table('billing_events')
    # ### end Alembic commands ###
