"""story user_created index

Revision ID: c1c035ea64c4
Revises: 1d1fa5426c98
Create Date: 2026-08-01 23:42:20.029799
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1c035ea64c4'
down_revision: Union[str, None] = '1d1fa5426c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index('ix_stories_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index('ix_stories_user_created')

    # ### end Alembic commands ###
