"""child profiles and story cast

Revision ID: f8549124ef00
Revises: 3793efbb78d8
Create Date: 2026-08-04 14:06:05.229632
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8549124ef00'
down_revision: Union[str, None] = '3793efbb78d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('age_band', sa.String(length=16), server_default='', nullable=False),
    sa.Column('age_band_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('companion_characters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=120), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companion_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companion_characters_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cast_json', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('reading_band', sa.String(length=16), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('reading_band')
        batch_op.drop_column('cast_json')

    with op.batch_alter_table('companion_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companion_characters_user_id'))

    op.drop_table('companion_characters')
    with op.batch_alter_table('child_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_profiles_user_id'))

    op.drop_table('child_profiles')
    # ### end Alembic commands ###
